<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/** Shopper watches for a store + set restock. */
final class Version20260912010000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add customer_set_alerts for store + set restock watches';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE customer_set_alerts (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, user_id INT NOT NULL, store_id INT NOT NULL, game VARCHAR(40) NOT NULL, set_code VARCHAR(40) NOT NULL, set_name VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX idx_customer_set_alert_store_set ON customer_set_alerts (store_id, game, set_code)');
        $this->addSql('CREATE UNIQUE INDEX uniq_customer_set_alert_watch ON customer_set_alerts (user_id, store_id, game, set_code)');
        $this->addSql('ALTER TABLE customer_set_alerts ADD CONSTRAINT FK_CSA_USER FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE customer_set_alerts ADD CONSTRAINT FK_CSA_STORE FOREIGN KEY (store_id) REFERENCES stores (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE customer_set_alerts DROP CONSTRAINT FK_CSA_USER');
        $this->addSql('ALTER TABLE customer_set_alerts DROP CONSTRAINT FK_CSA_STORE');
        $this->addSql('DROP TABLE customer_set_alerts');
    }
}
