<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260816120000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Store staff so owners can add employees with optional admin access';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE store_staff (
            id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            store_id INT NOT NULL,
            user_id INT NOT NULL,
            role VARCHAR(16) NOT NULL,
            created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            PRIMARY KEY (id)
        )');
        $this->addSql('CREATE INDEX IDX_STORE_STAFF_STORE ON store_staff (store_id)');
        $this->addSql('CREATE INDEX IDX_STORE_STAFF_USER ON store_staff (user_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_store_staff_store_user ON store_staff (store_id, user_id)');
        $this->addSql('ALTER TABLE store_staff ADD CONSTRAINT FK_STORE_STAFF_STORE FOREIGN KEY (store_id) REFERENCES stores (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE store_staff ADD CONSTRAINT FK_STORE_STAFF_USER FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE store_staff DROP CONSTRAINT FK_STORE_STAFF_STORE');
        $this->addSql('ALTER TABLE store_staff DROP CONSTRAINT FK_STORE_STAFF_USER');
        $this->addSql('DROP TABLE store_staff');
    }
}
