<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Platform patch notes: written by platform admins, readable by store admins
 * on their private Patch notes page.
 */
final class Version20260727110000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create patch_notes table';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE patch_notes (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(160) NOT NULL, body TEXT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE patch_notes');
    }
}
