<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Sell/Trade portal foundation: store-curated buy lists and customer sell
 * submissions with per-line offer snapshots.
 */
final class Version20260727130000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create buylist_entries, sell_submissions, sell_submission_items';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE buylist_entries (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, store_id INT NOT NULL, card_id UUID NOT NULL, offer_cents INT NOT NULL, wants_foil BOOLEAN NOT NULL, max_quantity INT DEFAULT NULL, notes VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_BUYLIST_STORE ON buylist_entries (store_id)');
        $this->addSql('CREATE INDEX IDX_BUYLIST_CARD ON buylist_entries (card_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_buylist_store_card_foil ON buylist_entries (store_id, card_id, wants_foil)');
        $this->addSql('ALTER TABLE buylist_entries ADD CONSTRAINT FK_BUYLIST_STORE FOREIGN KEY (store_id) REFERENCES stores (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE buylist_entries ADD CONSTRAINT FK_BUYLIST_CARD FOREIGN KEY (card_id) REFERENCES cards (id) ON DELETE CASCADE NOT DEFERRABLE');

        $this->addSql('CREATE TABLE sell_submissions (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, store_id INT NOT NULL, user_id INT NOT NULL, status VARCHAR(16) DEFAULT \'pending\' NOT NULL, total_offer_cents INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, decided_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_sell_submission_store_status ON sell_submissions (store_id, status)');
        $this->addSql('CREATE INDEX IDX_SELL_SUB_USER ON sell_submissions (user_id)');
        $this->addSql('ALTER TABLE sell_submissions ADD CONSTRAINT FK_SELL_SUB_STORE FOREIGN KEY (store_id) REFERENCES stores (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE sell_submissions ADD CONSTRAINT FK_SELL_SUB_USER FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE');

        $this->addSql('CREATE TABLE sell_submission_items (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, submission_id INT NOT NULL, card_id UUID DEFAULT NULL, card_name VARCHAR(255) NOT NULL, is_foil BOOLEAN NOT NULL, quantity INT NOT NULL, offer_cents_each INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_SELL_ITEM_SUBMISSION ON sell_submission_items (submission_id)');
        $this->addSql('ALTER TABLE sell_submission_items ADD CONSTRAINT FK_SELL_ITEM_SUBMISSION FOREIGN KEY (submission_id) REFERENCES sell_submissions (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE sell_submission_items ADD CONSTRAINT FK_SELL_ITEM_CARD FOREIGN KEY (card_id) REFERENCES cards (id) ON DELETE SET NULL NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE sell_submission_items');
        $this->addSql('DROP TABLE sell_submissions');
        $this->addSql('DROP TABLE buylist_entries');
    }
}
