<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Local commander synergy edges keyed by oracle id.
 *
 * Scryfall remains the card source (cards table). This table stores offline
 * signal weights — theme co-occurrence today, Moxfield/deck co-occurrence
 * later — so recommend requests stay local and store-scoped.
 */
final class Version20260804050000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add card_synergies for local commander recommendation weights';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE card_synergies (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, oracle_a UUID NOT NULL, oracle_b UUID NOT NULL, weight DOUBLE PRECISION NOT NULL, source VARCHAR(32) NOT NULL, shared_tags JSON DEFAULT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_card_synergy_pair_source ON card_synergies (oracle_a, oracle_b, source)');
        $this->addSql('CREATE INDEX idx_card_synergy_oracle_a ON card_synergies (oracle_a)');
        $this->addSql('CREATE INDEX idx_card_synergy_oracle_b ON card_synergies (oracle_b)');
        $this->addSql('CREATE INDEX idx_card_synergy_source ON card_synergies (source)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE card_synergies');
    }
}
