<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Multi-game catalog: games, game_sets, sealed_products, catalog_sync_runs,
 * sealed_inventory_items; cards gain game/set linkage + TCGplayer product
 * id. Seeds the five supported games with their TCGCSV category ids.
 * Existing cards keep game_id NULL, which the application reads as Magic.
 */
final class Version20260728020000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Games, game sets, sealed products, catalog sync runs, sealed inventory; cards game linkage';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE games (
            id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            code VARCHAR(32) NOT NULL,
            name VARCHAR(120) NOT NULL,
            tcgcsv_category_id INT DEFAULT NULL,
            position INT DEFAULT 0 NOT NULL,
            active BOOLEAN DEFAULT true NOT NULL,
            PRIMARY KEY (id)
        )');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_GAMES_CODE ON games (code)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_GAMES_TCGCSV_CATEGORY ON games (tcgcsv_category_id)');

        $this->addSql('CREATE TABLE game_sets (
            id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            game_id INT NOT NULL,
            tcgcsv_group_id INT NOT NULL,
            name VARCHAR(255) NOT NULL,
            code VARCHAR(40) DEFAULT NULL,
            release_date DATE DEFAULT NULL,
            updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            PRIMARY KEY (id)
        )');
        $this->addSql('CREATE UNIQUE INDEX uniq_game_set_tcgcsv_group ON game_sets (tcgcsv_group_id)');
        $this->addSql('CREATE INDEX idx_game_set_game ON game_sets (game_id, release_date)');
        $this->addSql('ALTER TABLE game_sets ADD CONSTRAINT FK_GAME_SETS_GAME FOREIGN KEY (game_id) REFERENCES games (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');

        $this->addSql('CREATE TABLE sealed_products (
            id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            game_id INT NOT NULL,
            game_set_id INT DEFAULT NULL,
            tcgcsv_product_id BIGINT NOT NULL,
            name VARCHAR(255) NOT NULL,
            image_url VARCHAR(1024) DEFAULT NULL,
            url VARCHAR(1024) DEFAULT NULL,
            market_price_cents INT DEFAULT NULL,
            low_price_cents INT DEFAULT NULL,
            updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            PRIMARY KEY (id)
        )');
        $this->addSql('CREATE UNIQUE INDEX uniq_sealed_tcgcsv_product ON sealed_products (tcgcsv_product_id)');
        $this->addSql('CREATE INDEX idx_sealed_game_name ON sealed_products (game_id, name)');
        $this->addSql('CREATE INDEX idx_sealed_set ON sealed_products (game_set_id)');
        $this->addSql('ALTER TABLE sealed_products ADD CONSTRAINT FK_SEALED_GAME FOREIGN KEY (game_id) REFERENCES games (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE sealed_products ADD CONSTRAINT FK_SEALED_SET FOREIGN KEY (game_set_id) REFERENCES game_sets (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');

        $this->addSql('CREATE TABLE catalog_sync_runs (
            id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            game_id INT NOT NULL,
            status VARCHAR(16) DEFAULT \'running\' NOT NULL,
            started_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            finished_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
            summary JSON DEFAULT NULL,
            error TEXT DEFAULT NULL,
            PRIMARY KEY (id)
        )');
        $this->addSql('CREATE INDEX idx_catalog_sync_started ON catalog_sync_runs (started_at)');
        $this->addSql('CREATE INDEX IDX_CATALOG_SYNC_GAME ON catalog_sync_runs (game_id)');
        $this->addSql('ALTER TABLE catalog_sync_runs ADD CONSTRAINT FK_CATALOG_SYNC_GAME FOREIGN KEY (game_id) REFERENCES games (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');

        $this->addSql('CREATE TABLE sealed_inventory_items (
            id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            store_id INT NOT NULL,
            sealed_product_id INT NOT NULL,
            quantity INT DEFAULT 0 NOT NULL,
            price_cents INT DEFAULT 0 NOT NULL,
            acquisition_cost_cents INT DEFAULT NULL,
            updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            PRIMARY KEY (id)
        )');
        $this->addSql('CREATE UNIQUE INDEX uniq_sealed_inventory_line ON sealed_inventory_items (store_id, sealed_product_id)');
        $this->addSql('CREATE INDEX idx_sealed_inventory_store ON sealed_inventory_items (store_id)');
        $this->addSql('CREATE INDEX IDX_SEALED_INV_PRODUCT ON sealed_inventory_items (sealed_product_id)');
        $this->addSql('ALTER TABLE sealed_inventory_items ADD CONSTRAINT FK_SEALED_INV_STORE FOREIGN KEY (store_id) REFERENCES stores (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE sealed_inventory_items ADD CONSTRAINT FK_SEALED_INV_PRODUCT FOREIGN KEY (sealed_product_id) REFERENCES sealed_products (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');

        $this->addSql('ALTER TABLE cards ADD game_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE cards ADD game_set_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE cards ADD tcgplayer_product_id BIGINT DEFAULT NULL');
        $this->addSql('ALTER TABLE cards ALTER set_code TYPE VARCHAR(40)');
        $this->addSql('ALTER TABLE cards ADD CONSTRAINT FK_CARDS_GAME FOREIGN KEY (game_id) REFERENCES games (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE cards ADD CONSTRAINT FK_CARDS_GAME_SET FOREIGN KEY (game_set_id) REFERENCES game_sets (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX IDX_CARDS_GAME ON cards (game_id)');
        $this->addSql('CREATE INDEX IDX_CARDS_GAME_SET ON cards (game_set_id)');

        // Supported games and their TCGplayer/TCGCSV category ids.
        $this->addSql("INSERT INTO games (code, name, tcgcsv_category_id, position, active) VALUES
            ('mtg', 'Magic: The Gathering', 1, 0, true),
            ('pokemon', 'Pokémon', 3, 1, true),
            ('onepiece', 'One Piece Card Game', 68, 2, true),
            ('fab', 'Flesh and Blood', 62, 3, true),
            ('riftbound', 'Riftbound: League of Legends', 89, 4, true)");
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE cards DROP CONSTRAINT FK_CARDS_GAME');
        $this->addSql('ALTER TABLE cards DROP CONSTRAINT FK_CARDS_GAME_SET');
        $this->addSql('DROP INDEX IDX_CARDS_GAME');
        $this->addSql('DROP INDEX IDX_CARDS_GAME_SET');
        $this->addSql('ALTER TABLE cards DROP game_id');
        $this->addSql('ALTER TABLE cards DROP game_set_id');
        $this->addSql('ALTER TABLE cards DROP tcgplayer_product_id');
        $this->addSql('ALTER TABLE cards ALTER set_code TYPE VARCHAR(10)');
        $this->addSql('DROP TABLE sealed_inventory_items');
        $this->addSql('DROP TABLE catalog_sync_runs');
        $this->addSql('DROP TABLE sealed_products');
        $this->addSql('DROP TABLE game_sets');
        $this->addSql('DROP TABLE games');
    }
}
