<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260826010000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'PayPal store accounts, order payment provider, platform billing provider, webhook log.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql("ALTER TABLE orders ADD payment_provider VARCHAR(16) DEFAULT NULL");
        $this->addSql("ALTER TABLE stores ADD billing_provider VARCHAR(16) DEFAULT 'square' NOT NULL");
        $this->addSql('CREATE TABLE paypal_webhook_events (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, event_id VARCHAR(128) NOT NULL, type VARCHAR(64) NOT NULL, merchant_id VARCHAR(128) DEFAULT NULL, status VARCHAR(16) NOT NULL, note TEXT DEFAULT NULL, received_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_PAYPAL_WEBHOOK_EVENT ON paypal_webhook_events (event_id)');
        $this->addSql('CREATE INDEX IDX_PAYPAL_WEBHOOK_TYPE ON paypal_webhook_events (type)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE paypal_webhook_events');
        $this->addSql('ALTER TABLE orders DROP payment_provider');
        $this->addSql('ALTER TABLE stores DROP billing_provider');
    }
}
