<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260805040000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Subscription charge history, so billing can be reviewed month over month';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE subscription_charges (
            id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            store_id INT NOT NULL,
            plan_key VARCHAR(32) DEFAULT NULL,
            amount_cents INT NOT NULL,
            status VARCHAR(16) NOT NULL,
            reference VARCHAR(128) DEFAULT NULL,
            failure_reason TEXT DEFAULT NULL,
            attempt INT DEFAULT 0 NOT NULL,
            created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            PRIMARY KEY (id)
        )');
        $this->addSql('CREATE INDEX IDX_SUBSCRIPTION_CHARGE_STORE ON subscription_charges (store_id)');
        $this->addSql('CREATE INDEX IDX_SUBSCRIPTION_CHARGE_CREATED ON subscription_charges (created_at)');
        $this->addSql('ALTER TABLE subscription_charges ADD CONSTRAINT FK_SUBSCRIPTION_CHARGE_STORE FOREIGN KEY (store_id) REFERENCES stores (id) ON DELETE CASCADE');

        // Seed history from what the Store rows already remember, so the admin
        // view is not empty for stores that paid before this table existed.
        // Only the most recent collection is recoverable; earlier ones are gone.
        $this->addSql(<<<'SQL'
            INSERT INTO subscription_charges (store_id, plan_key, amount_cents, status, reference, attempt, created_at)
            SELECT id,
                   plan_key,
                   CASE plan_key WHEN 'pro' THEN 4900 WHEN 'enterprise' THEN 19900 ELSE 0 END,
                   'paid',
                   payment_reference,
                   0,
                   last_charged_at
            FROM stores
            WHERE last_charged_at IS NOT NULL
              AND plan_key IN ('pro', 'enterprise')
            SQL);
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE subscription_charges');
    }
}
