<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Store credit ledger (append-only transactions summed into balances,
 * credit applied tracked on orders) and saved decks (user-owned,
 * store-independent card lists).
 */
final class Version20260728010000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Store credit transactions + orders.credit_applied_cents; decks + deck_cards';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE store_credit_transactions (
            id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            store_id INT NOT NULL,
            user_id INT NOT NULL,
            amount_cents INT NOT NULL,
            kind VARCHAR(24) NOT NULL,
            sell_submission_id INT DEFAULT NULL,
            order_id INT DEFAULT NULL,
            note VARCHAR(255) DEFAULT NULL,
            created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            PRIMARY KEY (id)
        )');
        $this->addSql('CREATE INDEX idx_store_credit_user_store ON store_credit_transactions (user_id, store_id, created_at)');
        $this->addSql('CREATE INDEX IDX_SCT_STORE ON store_credit_transactions (store_id)');
        $this->addSql('CREATE INDEX IDX_SCT_SUBMISSION ON store_credit_transactions (sell_submission_id)');
        $this->addSql('CREATE INDEX IDX_SCT_ORDER ON store_credit_transactions (order_id)');
        $this->addSql('ALTER TABLE store_credit_transactions ADD CONSTRAINT FK_SCT_STORE FOREIGN KEY (store_id) REFERENCES stores (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE store_credit_transactions ADD CONSTRAINT FK_SCT_USER FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE store_credit_transactions ADD CONSTRAINT FK_SCT_SUBMISSION FOREIGN KEY (sell_submission_id) REFERENCES sell_submissions (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE store_credit_transactions ADD CONSTRAINT FK_SCT_ORDER FOREIGN KEY (order_id) REFERENCES orders (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');

        $this->addSql('ALTER TABLE orders ADD credit_applied_cents INT DEFAULT 0 NOT NULL');

        $this->addSql('CREATE TABLE decks (
            id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            user_id INT NOT NULL,
            name VARCHAR(120) NOT NULL,
            format VARCHAR(40) DEFAULT NULL,
            notes TEXT DEFAULT NULL,
            created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            PRIMARY KEY (id)
        )');
        $this->addSql('CREATE INDEX idx_deck_user_updated ON decks (user_id, updated_at)');
        $this->addSql('ALTER TABLE decks ADD CONSTRAINT FK_DECKS_USER FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');

        $this->addSql('CREATE TABLE deck_cards (
            id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            deck_id INT NOT NULL,
            card_id UUID DEFAULT NULL,
            card_name VARCHAR(255) NOT NULL,
            quantity INT NOT NULL,
            PRIMARY KEY (id)
        )');
        $this->addSql('CREATE INDEX IDX_DECK_CARDS_DECK ON deck_cards (deck_id)');
        $this->addSql('CREATE INDEX IDX_DECK_CARDS_CARD ON deck_cards (card_id)');
        $this->addSql('ALTER TABLE deck_cards ADD CONSTRAINT FK_DECK_CARDS_DECK FOREIGN KEY (deck_id) REFERENCES decks (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE deck_cards ADD CONSTRAINT FK_DECK_CARDS_CARD FOREIGN KEY (card_id) REFERENCES cards (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE deck_cards');
        $this->addSql('DROP TABLE decks');
        $this->addSql('DROP TABLE store_credit_transactions');
        $this->addSql('ALTER TABLE orders DROP credit_applied_cents');
    }
}
