<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Commander Intelligence & Synergy Engine storage.
 *
 * Three tables, split by how long the data is worth keeping:
 *
 *  - reference_decks / reference_deck_cards: harvested community decklists.
 *    A working set — this is the deck-membership matrix co-occurrence reads,
 *    and it can be pruned once aggregates settle.
 *  - commander_strategy_stats: how much data we hold per commander/strategy,
 *    so confidence and the fallback ladder are grounded in real sample sizes.
 *  - commander_card_stats: the durable derived statistics (inclusion rate,
 *    commander affinity, strategy affinity) that recommendations actually read.
 *
 * There is deliberately no card-pair table: pairs are O(n²) per deck and would
 * run to nine figures of rows across every commander and strategy. Relationships
 * are computed on demand from the membership rows instead.
 */
final class Version20260820100000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add reference deck + commander intelligence aggregate tables';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(<<<'SQL'
            CREATE TABLE reference_decks (
                id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                provider VARCHAR(32) NOT NULL,
                external_id VARCHAR(128) NOT NULL,
                commander_oracle_id UUID NOT NULL,
                partner_oracle_id UUID DEFAULT NULL,
                name VARCHAR(255) NOT NULL,
                popularity DOUBLE PRECISION NOT NULL,
                bracket INT DEFAULT NULL,
                provider_tags JSON NOT NULL,
                strategy_ids JSON NOT NULL,
                card_count INT NOT NULL,
                url VARCHAR(512) DEFAULT NULL,
                source_updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
                fetched_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE UNIQUE INDEX uniq_reference_deck_external ON reference_decks (provider, external_id)');
        $this->addSql('CREATE INDEX idx_reference_deck_commander ON reference_decks (commander_oracle_id, popularity)');
        $this->addSql('CREATE INDEX idx_reference_deck_fetched ON reference_decks (fetched_at)');

        $this->addSql(<<<'SQL'
            CREATE TABLE reference_deck_cards (
                id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                reference_deck_id INT NOT NULL,
                oracle_id UUID NOT NULL,
                quantity SMALLINT NOT NULL,
                role_hint VARCHAR(64) DEFAULT NULL,
                PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE UNIQUE INDEX uniq_reference_deck_card ON reference_deck_cards (reference_deck_id, oracle_id)');
        $this->addSql('CREATE INDEX idx_reference_deck_card_oracle ON reference_deck_cards (oracle_id)');
        $this->addSql(<<<'SQL'
            ALTER TABLE reference_deck_cards
                ADD CONSTRAINT fk_reference_deck_cards_deck
                FOREIGN KEY (reference_deck_id) REFERENCES reference_decks (id)
                ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);

        $this->addSql(<<<'SQL'
            CREATE TABLE commander_strategy_stats (
                id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                commander_oracle_id UUID NOT NULL,
                strategy_id VARCHAR(64) NOT NULL,
                deck_count INT NOT NULL,
                sample_size INT NOT NULL,
                confidence DOUBLE PRECISION NOT NULL,
                source VARCHAR(32) NOT NULL,
                updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE UNIQUE INDEX uniq_commander_strategy ON commander_strategy_stats (commander_oracle_id, strategy_id)');
        $this->addSql('CREATE INDEX idx_commander_strategy_commander ON commander_strategy_stats (commander_oracle_id, deck_count)');

        $this->addSql(<<<'SQL'
            CREATE TABLE commander_card_stats (
                id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                commander_oracle_id UUID NOT NULL,
                strategy_id VARCHAR(64) NOT NULL,
                oracle_id UUID NOT NULL,
                deck_count INT NOT NULL,
                sample_size INT NOT NULL,
                inclusion_rate DOUBLE PRECISION NOT NULL,
                commander_affinity DOUBLE PRECISION NOT NULL,
                strategy_affinity DOUBLE PRECISION NOT NULL,
                average_quantity DOUBLE PRECISION NOT NULL,
                base_score DOUBLE PRECISION NOT NULL,
                confidence DOUBLE PRECISION NOT NULL,
                role_hint VARCHAR(64) DEFAULT NULL,
                updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE UNIQUE INDEX uniq_commander_card_stat ON commander_card_stats (commander_oracle_id, strategy_id, oracle_id)');
        $this->addSql('CREATE INDEX idx_commander_card_stat_lookup ON commander_card_stats (commander_oracle_id, strategy_id, base_score)');
        $this->addSql('CREATE INDEX idx_commander_card_stat_oracle ON commander_card_stats (oracle_id)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE reference_deck_cards DROP CONSTRAINT fk_reference_deck_cards_deck');
        $this->addSql('DROP TABLE commander_card_stats');
        $this->addSql('DROP TABLE commander_strategy_stats');
        $this->addSql('DROP TABLE reference_deck_cards');
        $this->addSql('DROP TABLE reference_decks');
    }
}
