<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260805030000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Subscription billing periods with dunning, and a Square webhook event log';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('ALTER TABLE stores ADD current_period_end TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
        $this->addSql('ALTER TABLE stores ADD last_charged_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
        $this->addSql('ALTER TABLE stores ADD billing_attempts INT DEFAULT 0 NOT NULL');
        $this->addSql('ALTER TABLE stores ADD next_attempt_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');

        // Renewals only fire once the period end has passed, so existing paid
        // subscribers are given a full period from now. A null would be the
        // other safe choice but would leave them never billed; either way the
        // deliberate outcome is that nobody is charged the moment this deploys.
        $this->addSql("UPDATE stores SET current_period_end = NOW() + INTERVAL '1 month' WHERE subscription_status = 'active' AND payment_card_id IS NOT NULL");

        // Square retries delivery and can send an event more than once; the
        // unique event id is what makes replaying a refund a no-op.
        $this->addSql('CREATE TABLE square_webhook_events (
            id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            event_id VARCHAR(128) NOT NULL,
            type VARCHAR(64) NOT NULL,
            merchant_id VARCHAR(128) DEFAULT NULL,
            status VARCHAR(16) NOT NULL,
            note TEXT DEFAULT NULL,
            received_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            PRIMARY KEY (id)
        )');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_SQUARE_WEBHOOK_EVENT ON square_webhook_events (event_id)');
        $this->addSql('CREATE INDEX IDX_SQUARE_WEBHOOK_TYPE ON square_webhook_events (type)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE square_webhook_events');
        $this->addSql('ALTER TABLE stores DROP current_period_end');
        $this->addSql('ALTER TABLE stores DROP last_charged_at');
        $this->addSql('ALTER TABLE stores DROP billing_attempts');
        $this->addSql('ALTER TABLE stores DROP next_attempt_at');
    }
}
