<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260822210000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Compliance intake: age, store licenses, private documents, privacy requests, order disputes.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('ALTER TABLE users ADD date_of_birth DATE DEFAULT NULL');
        $this->addSql('ALTER TABLE users ADD terms_accepted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
        $this->addSql('ALTER TABLE stores ADD compliance JSON DEFAULT NULL');
        $this->addSql('ALTER TABLE orders ADD dispute_status VARCHAR(16) DEFAULT NULL');
        $this->addSql('ALTER TABLE orders ADD dispute_reason VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE orders ADD disputed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
        $this->addSql('CREATE TABLE compliance_documents (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, owner_id INT NOT NULL, store_id INT DEFAULT NULL, kind VARCHAR(32) NOT NULL, storage_key VARCHAR(80) NOT NULL, original_filename VARCHAR(255) NOT NULL, mime VARCHAR(64) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_COMPLIANCE_DOC_OWNER ON compliance_documents (owner_id)');
        $this->addSql('CREATE INDEX IDX_COMPLIANCE_DOC_STORE ON compliance_documents (store_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_COMPLIANCE_DOC_KEY ON compliance_documents (storage_key)');
        $this->addSql('ALTER TABLE compliance_documents ADD CONSTRAINT FK_COMPLIANCE_DOC_OWNER FOREIGN KEY (owner_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE compliance_documents ADD CONSTRAINT FK_COMPLIANCE_DOC_STORE FOREIGN KEY (store_id) REFERENCES stores (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE TABLE privacy_requests (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(32) NOT NULL, status VARCHAR(32) NOT NULL, email VARCHAR(180) NOT NULL, name VARCHAR(120) NOT NULL, details TEXT DEFAULT NULL, california_resident BOOLEAN NOT NULL, admin_notes TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, completed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_PRIVACY_REQUEST_STATUS ON privacy_requests (status)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE compliance_documents DROP CONSTRAINT FK_COMPLIANCE_DOC_OWNER');
        $this->addSql('ALTER TABLE compliance_documents DROP CONSTRAINT FK_COMPLIANCE_DOC_STORE');
        $this->addSql('DROP TABLE compliance_documents');
        $this->addSql('DROP TABLE privacy_requests');
        $this->addSql('ALTER TABLE users DROP date_of_birth');
        $this->addSql('ALTER TABLE users DROP terms_accepted_at');
        $this->addSql('ALTER TABLE stores DROP compliance');
        $this->addSql('ALTER TABLE orders DROP dispute_status');
        $this->addSql('ALTER TABLE orders DROP dispute_reason');
        $this->addSql('ALTER TABLE orders DROP disputed_at');
    }
}
