import type { TrainingBeat, TrainingModule } from './types'

/**
 * Each beat opens the live page and points at a real control.
 * Demo fills/clicks are safe: they never connect Square, save settings, or add stock.
 */

export const TRAINING_CATEGORIES: { id: TrainingModule['category']; label: string }[] = [
  { id: 'start', label: 'Get started' },
  { id: 'inventory', label: 'Inventory' },
  { id: 'sales', label: 'Sales' },
  { id: 'storefront', label: 'Storefront' },
]

function beat(
  title: string,
  narration: string,
  href: string,
  target: string,
  callout: string,
  extra: Partial<
    Pick<
      TrainingBeat,
      | 'hrefLabel'
      | 'place'
      | 'demo'
      | 'focus'
      | 'completion'
      | 'prepare'
      | 'scrollTarget'
      | 'spotlightTarget'
      | 'tooltipTarget'
    >
  > = {},
): TrainingBeat {
  return { title, narration, href, target, callout, focus: 'target-if-needed', completion: 'narration', ...extra }
}

export const TRAINING_MODULES: TrainingModule[] = [
  {
    id: 'see-your-shop',
    title: 'See what shoppers see',
    summary: 'Walk the public storefront, then jump to the admin pages that control each block.',
    minutes: 5,
    category: 'start',
    beats: [
      beat(
        'This is the live shop',
        'Shoppers never see this admin. They land on your public storefront at slash s, then your store slug. The hero, the shortcuts, and the singles grid are all driven by settings you control here.',
        '/',
        'Search Cards',
        'Shoppers land here',
        { hrefLabel: 'Open storefront', place: 'bottom' },
      ),
      beat(
        'Jump into admin',
        'If you are already signed in as staff, Admin workspace on the hero jumps straight into this dashboard. Do not click it in this lesson — use View storefront the other way when you want to check work after you save.',
        '/',
        'Admin workspace',
        'Staff jump in here',
        { hrefLabel: 'Open storefront', place: 'left' },
      ),
      beat(
        'Search a card',
        'Search Cards scrolls shoppers to the catalog. This is the job most people came to do. If this tile is empty later, you have not stocked singles yet.',
        '/',
        'Search Cards',
        'Customer search',
        { hrefLabel: 'Open storefront', place: 'bottom' },
      ),
      beat(
        'Case, events, sell',
        'Case Cards, Event calendar, and Sell/Trade are the other counters. Each tile opens a public page. If a tile looks empty, the matching admin page is not filled in yet.',
        '/',
        'Case Cards',
        'Physical case page',
        { hrefLabel: 'Open storefront', place: 'bottom' },
      ),
      beat(
        'Event calendar',
        'Event calendar is the public board. You write that copy under Events in admin. Empty listings mean shoppers see no upcoming nights.',
        '/',
        'Event calendar',
        'Public calendar',
        { hrefLabel: 'Open storefront', place: 'bottom' },
      ),
      beat(
        'Sell or trade',
        'Sell/Trade is the public buy list. Rates and wanted cards are set under Sell / Trade in admin. Shoppers submit there; you review at the counter.',
        '/',
        'Sell/Trade',
        'Public buy list',
        { hrefLabel: 'Open storefront', place: 'bottom' },
      ),
      beat(
        'Branding owns the look',
        'Colors, logo, and how cards render are not a separate website. Open Branding when you want the hero and the card layout to match the shop you just walked.',
        '/admin/branding',
        'Branding',
        'Open Branding',
        { hrefLabel: 'Open Branding', place: 'right' },
      ),
    ],
  },
  {
    id: 'take-cards',
    title: 'Take live card payments',
    summary: 'Connect Square, finish the go-live checklist, then complete a paid pickup on Orders.',
    minutes: 6,
    category: 'start',
    beats: [
      beat(
        'Open Payments',
        'Card checkout lives under Payments in the Commerce group. Shopper money never settles to LGS Card Vault. Your Square seller account is merchant of record.',
        '/admin/payments',
        'Payments',
        'Open Payments',
        { hrefLabel: 'Open Payments', place: 'right' },
      ),
      beat(
        'Customer checkout card',
        'This Square card is checkout for shoppers. Platform billing, if you see it above, is a different thing — that is how the store pays for the software.',
        '/admin/payments',
        'Square',
        'Shopper checkout',
        { hrefLabel: 'Open Payments', place: 'right' },
      ),
      beat(
        'Read the connection badge',
        'If this badge says Not connected, customers cannot pay by card yet. Connected means checkout can charge this location. Needs attention means Square returned an error — refresh and try again.',
        '/admin/payments',
        'Square status',
        'Connection status',
        { hrefLabel: 'Open Payments', place: 'left' },
      ),
      beat(
        'Connect Square — do not click yet',
        'When you are ready, press Connect Square and approve access for this store. Use sandbox only while testing. In production, sign in as the real seller. We will not click it in this lesson.',
        '/admin/payments',
        'Connect Square|Reconnect',
        'Connect Square',
        { hrefLabel: 'Open Payments', place: 'left' },
      ),
      beat(
        'Finish the go-live checklist',
        'Connecting the app is not enough. In Square Dashboard, for this location, turn on the correct sales tax. In a sales-tax state, card checkout refuses to complete if Square quotes zero tax. Alaska, Delaware, Montana, New Hampshire, and Oregon can complete at zero.',
        '/admin/payments',
        'Go-live checklist',
        'Tax and go-live',
        { hrefLabel: 'Open Payments', place: 'top', focus: 'target' },
      ),
      beat(
        'Never type a card number here',
        'Shoppers enter cards only inside Square’s form. Do not type a card number into this app, email, or chat. Chargebacks are answered in Square. Gather pickup proof — name, time, staff notes.',
        '/admin/payments',
        'Go-live checklist',
        'Cards stay in Square',
        { hrefLabel: 'Open Payments', place: 'top', focus: 'target' },
      ),
      beat(
        'Finish the pickup on Orders',
        'After a card payment, the work moves to Orders. Open a paid pickup and use Accept order, then Ready for pickup, then Mark delivered when they collect. We will walk that queue next if you open Fill pickup orders.',
        '/admin/orders',
        'Orders',
        'Then finish on Orders',
        { hrefLabel: 'Open Orders', place: 'right' },
      ),
    ],
  },
  {
    id: 'add-singles',
    title: 'Add singles',
    summary: 'Pick the game, search the catalog, choose a printing, then set qty, condition, finish, and price.',
    minutes: 6,
    category: 'inventory',
    beats: [
      beat(
        'Open Singles',
        'Singles is the first item under Inventory. This is where you add one printing at a time. A spreadsheet belongs on Imports instead.',
        '/admin',
        'Singles',
        'Open Singles',
        { hrefLabel: 'Open Singles', place: 'right' },
      ),
      beat(
        'Pick the game first',
        'Singles is game-scoped. Choose Magic, Pokémon, or another game you carry. The catalog search and the stock list both stay on that game, so you do not mix printings.',
        '/admin',
        'Manage inventory for',
        'Choose the game',
        { hrefLabel: 'Open Singles', place: 'bottom', prepare: { selectFirstGame: 'Manage inventory for' } },
      ),
      beat(
        'Type the card name',
        'Add inventory searches the game catalog — every printing that exists, not only what you already stock. Type the card name here. I will type Lightning Bolt as an example. This does not add stock yet.',
        '/admin',
        'Card name',
        'Type the card name',
        { hrefLabel: 'Open Singles', place: 'right', prepare: { fillTarget: 'Card name', fill: 'Lightning Bolt' } },
      ),
      beat(
        'Optional set and finish',
        'Set code narrows to one printing, like MH2. Finish filters foil or nonfoil in that game’s own words. Leave them blank for a first search.',
        '/admin',
        'Set',
        'Optional set code',
        { hrefLabel: 'Open Singles', place: 'bottom' },
      ),
      beat(
        'Search the catalog',
        'Press Search. Results are catalog rows you can add. We will run that search now so you can see hits. We will not add a card in this lesson.',
        '/admin',
        'Search catalog',
        'Search',
        {
          hrefLabel: 'Open Singles',
          place: 'left',
          focus: 'target',
          scrollTarget: 'Card name',
          prepare: { fillTarget: 'Card name', fill: 'Lightning Bolt' },
        },
      ),
      beat(
        'Pick a printing',
        'Click the printing you actually have on the shelf — same set and collector number. The editor below is where quantity, condition, finish, and price live. If no Lightning Bolt appears, the catalog for this game is still syncing.',
        '/admin',
        'Lightning Bolt',
        'Pick this printing',
        {
          hrefLabel: 'Open Singles',
          place: 'right',
          prepare: { fillTarget: 'Card name', fill: 'Lightning Bolt' },
          demo: { thenClick: 'Search catalog', waitFor: { target: 'Lightning Bolt' } },
        },
      ),
      beat(
        'Quantity, finish, condition',
        'When a printing is selected, set how many copies, foil or nonfoil, and condition. Market is a snapshot, not a rule. Edit sell price if your shop sells above or below that number.',
        '/admin',
        'Quantity',
        'Qty, finish, condition',
        {
          hrefLabel: 'Open Singles',
          place: 'right',
          focus: 'target',
          scrollTarget: 'Quantity',
          prepare: { selectGuide: 'Lightning Bolt', waitFor: { target: 'Quantity' } },
          demo: { thenClick: 'Lightning Bolt', waitFor: { target: 'Quantity' } },
        },
      ),
      beat(
        'Set the sell price',
        'Sell price is what shoppers pay. Your cost per copy is optional and powers profit reports. Press the Add button only when those fields are right. We will not add from this lesson.',
        '/admin',
        'Sell price ($)',
        'Your sell price',
        {
          hrefLabel: 'Open Singles',
          place: 'right',
          focus: 'target',
          scrollTarget: 'Sell price ($)',
          prepare: { selectGuide: 'Lightning Bolt', waitFor: { target: 'Sell price ($)' } },
        },
      ),
      beat(
        'Find it in stock later',
        'After a card is added, it lands in the inventory list on this same page. Search stock filters what you already listed. Edit price or quantity from that card.',
        '/admin',
        'Search stock',
        'Your in-stock list',
        { hrefLabel: 'Open Singles', place: 'right', focus: 'target', scrollTarget: 'Search stock' },
      ),
    ],
  },
  {
    id: 'import-csv',
    title: 'Import a spreadsheet',
    summary: 'Game, type, upload, preview, import — then watch the run and fix failed rows.',
    minutes: 6,
    category: 'inventory',
    beats: [
      beat(
        'Open Imports',
        'Imports is the path for a whole collection or a buylist file. The wizard is always the same five beats: game, singles or sealed, upload, preview, then import.',
        '/admin/csv',
        'Imports',
        'Open Imports',
        { hrefLabel: 'Open Imports', place: 'right' },
      ),
      beat(
        'Five steps, in order',
        'The rail at the top is the whole process. Nothing is written until the last step. Large files resolve against the catalog in batches, so give them a few minutes.',
        '/admin/csv',
        'Import inventory',
        'The five-step wizard',
        { hrefLabel: 'Open Imports', place: 'bottom' },
      ),
      beat(
        'Step 1 — pick the game',
        'First, choose which game this sheet belongs to. A Pokémon file on Magic will fail every row. Click the game you are importing for, then the next step unlocks.',
        '/admin/csv',
        'Which game',
        'Step 1 — game',
        { hrefLabel: 'Open Imports', place: 'bottom', prepare: { selectFirstGame: 'Import for' } },
      ),
      beat(
        'Step 2 — singles or sealed',
        'Type is next. Singles are individual cards with condition and foil. Sealed is boxes, bundles, and decks. The sample CSV changes to match.',
        '/admin/csv',
        'Type',
        'Step 2 — type',
        { hrefLabel: 'Open Imports', place: 'bottom', prepare: { selectFirstGame: 'Import for', waitFor: { target: 'Type' } }, demo: { thenClick: 'Singles', waitFor: { target: 'Upload' } } },
      ),
      beat(
        'Step 3 — upload the CSV',
        'Download the sample first if you need the column names. Then choose your file. The server reads it and builds a preview. Closing the tab after you confirm does not stop a run that has already started.',
        '/admin/csv',
        'Upload',
        'Step 3 — upload',
        {
          hrefLabel: 'Open Imports',
          place: 'bottom',
          prepare: { selectFirstGame: 'Import for', thenClick: 'Singles', waitFor: { target: 'Upload' } },
        },
      ),
      beat(
        'Step 4 — preview the mapping',
        'Preview shows how rows resolve against the catalog: matched, invalid, and total quantity. Fix names in the sheet if too many rows miss. Do not import until the sample looks right.',
        '/admin/csv',
        'Preview',
        'Step 4 — preview',
        {
          hrefLabel: 'Open Imports',
          place: 'bottom',
          prepare: { selectFirstGame: 'Import for', thenClick: 'Singles', waitFor: { target: 'Preview' } },
        },
      ),
      beat(
        'Step 5 — import',
        'Import writes the rows. Stay until the progress bar hits 100 percent. The latest import card below the wizard shows rows, imported, and failed.',
        '/admin/csv',
        'Import',
        'Step 5 — write stock',
        {
          hrefLabel: 'Open Imports',
          place: 'bottom',
          prepare: { selectFirstGame: 'Import for', thenClick: 'Singles', waitFor: { target: 'Import' } },
        },
      ),
      beat(
        'Watch the latest run',
        'Latest import is the current or last job. Failed is the number to clear. Open that run, search the catalog, and place missed cards by hand. Do not re-upload the whole list unless you intend to add quantity again.',
        '/admin/csv',
        'Failed|Import inventory',
        'Failed rows land here',
        { hrefLabel: 'Open Imports', place: 'left' },
      ),
    ],
  },
  {
    id: 'sealed',
    title: 'Stock sealed product',
    summary: 'Pick the game, search the sealed catalog, then add boxes, bundles, and decks.',
    minutes: 4,
    category: 'inventory',
    beats: [
      beat(
        'Open Sealed',
        'Boxes, bundles, and decks do not live on Singles. Open Sealed under Inventory.',
        '/admin/sealed',
        'Sealed',
        'Open Sealed',
        { hrefLabel: 'Open Sealed', place: 'right' },
      ),
      beat(
        'Pick the game',
        'Same rule as singles: one game at a time. The in-stock list and the catalog underneath both follow this switcher.',
        '/admin/sealed',
        'Manage sealed for',
        'Choose the game',
        { hrefLabel: 'Open Sealed', place: 'bottom', prepare: { selectFirstGame: 'Manage sealed for' } },
      ),
      beat(
        'What you already stock',
        'The first card is what this store already carries. Edit quantity or price on a line, or remove it if it left the shelf.',
        '/admin/sealed',
        'sealed in stock',
        'In-stock sealed',
        { hrefLabel: 'Open Sealed', place: 'right' },
      ),
      beat(
        'Search the sealed catalog',
        'Under the in-stock list, search the sealed catalog for the product on the shelf. Prices can start from the market snapshot. Change the price before you add if your shop sells above or below that number.',
        '/admin/sealed',
        'Search sealed',
        'Search sealed products',
        { hrefLabel: 'Open Sealed', place: 'bottom' },
      ),
    ],
  },
  {
    id: 'cases',
    title: 'Display cases',
    summary: 'Name the physical case, add it, then section it and print pull or stocking sheets.',
    minutes: 5,
    category: 'inventory',
    beats: [
      beat(
        'Open Case Cards',
        'Case Cards tracks what sits in a real case on the floor. Open it under Inventory.',
        '/admin/case-cards',
        'Case Cards',
        'Open Case Cards',
        { hrefLabel: 'Open Case Cards', place: 'right' },
      ),
      beat(
        'Name the physical case',
        'Name it the way staff say it: front counter, wall case, mythic binder. That name is what pull sheets print.',
        '/admin/case-cards',
        'New case name',
        'Name the case',
        { hrefLabel: 'Open Case Cards', place: 'right', demo: { fill: 'Front counter case' } },
      ),
      beat(
        'Add the case',
        'Add case creates it. Then split it into sections so each tray has its own list. We will not create one from this lesson.',
        '/admin/case-cards',
        'Add case',
        'Create the case',
        { hrefLabel: 'Open Case Cards', place: 'left', focus: 'target', scrollTarget: 'Add case', prepare: { fillTarget: 'New case name', fill: 'Front counter case', waitFor: { target: 'Add case' } } },
      ),
      beat(
        'Sections, then sheets',
        'After the case exists, add sections and drop listings into each one. Print a pull sheet when an order needs cards from that case, or a stocking sheet when you are filling empty slots. The public Case Cards page only shows what you have assigned.',
        '/admin/case-cards',
        'Display cases',
        'Then section it',
        { hrefLabel: 'Open Case Cards', place: 'bottom' },
      ),
    ],
  },
  {
    id: 'orders',
    title: 'Fill pickup orders',
    summary: 'Read the queue, open a pickup, Accept order, Ready for pickup, then Mark delivered.',
    minutes: 6,
    category: 'sales',
    beats: [
      beat(
        'Open Orders',
        'Orders is the counter queue. There is no shipping. Paid online is already charged through Square. Pay-in-store is reserved until they pay at the register.',
        '/admin/orders',
        'Orders',
        'Open Orders',
        { hrefLabel: 'Open Orders', place: 'right' },
      ),
      beat(
        'This is the queue',
        'Order Management is the full list. Start with what is waiting, not what is already delivered.',
        '/admin/orders',
        'Order Management',
        'The counter queue',
        { hrefLabel: 'Open Orders', place: 'bottom' },
      ),
      beat(
        'Pending is the work',
        'Total Orders Pending is what you should clear first. A new paid or reserved pickup lands here.',
        '/admin/orders',
        'Total Orders Pending',
        'Clear these first',
        { hrefLabel: 'Open Orders', place: 'bottom' },
      ),
      beat(
        'Filter to Pending',
        'The Pending tab is only orders that still need Accept order. Processing is already accepted. Ready for pickup is waiting at the counter.',
        '/admin/orders',
        'Pending tab',
        'Pending tab',
        { hrefLabel: 'Open Orders', place: 'bottom' },
      ),
      beat(
        'Open the row menu',
        'Each pickup has an actions menu on the right. I will open the first one so you can see Accept order. Confirm the name matches the person at the counter before you hand product over.',
        '/admin/orders',
        'Order actions',
        'Open actions',
        { hrefLabel: 'Open Orders', place: 'left', focus: 'target', scrollTarget: 'Order actions', prepare: { thenClick: 'Pending tab', waitFor: { target: 'Order actions' } }, demo: { thenClick: 'Order actions' } },
      ),
      beat(
        'Accept the order',
        'Accept order means you are pulling the cards. It does not mark them collected. We will not click it here. After you accept, the next action is Ready for pickup.',
        '/admin/orders',
        'Accept order|Orders List',
        'Accept order',
        { hrefLabel: 'Open Orders', place: 'left' },
      ),
      beat(
        'Ready, then delivered',
        'Ready for pickup means the stack is at the counter. When they collect, Mark delivered. Refunds go through Square from this same menu. If Square opens a dispute, a flag appears on the row. We do not auto-restock a disputed order.',
        '/admin/orders',
        'Ready for pickup tab',
        'Then ready for pickup',
        { hrefLabel: 'Open Orders', place: 'bottom' },
      ),
    ],
  },
  {
    id: 'buy-list',
    title: 'Buy and trade from the public',
    summary: 'Set credit and cash rates, publish wanted cards, then review submissions at the counter.',
    minutes: 7,
    category: 'sales',
    beats: [
      beat(
        'Open Sell / Trade',
        'Sell / Trade is your public buy list and the inbox for shopper submissions. Open it under Commerce.',
        '/admin/sell-trade',
        'Sell / Trade',
        'Open Sell / Trade',
        { hrefLabel: 'Open Sell / Trade', place: 'right' },
      ),
      beat(
        'Submissions land here',
        'Sell submissions is the inbox. Needs review is a new offer. Accepted is a deal you already said yes to, waiting for the cards at the counter.',
        '/admin/sell-trade',
        'sell-submissions',
        'The inbox',
        { hrefLabel: 'Open Sell / Trade', place: 'bottom' },
      ),
      beat(
        'Needs review',
        'Start on Needs review. Open Review on a row, accept or trim lines, print a counter sheet, then accept the offer. Complete and stock inventory only when you take the cards in person.',
        '/admin/sell-trade',
        'Needs review',
        'New offers',
        { hrefLabel: 'Open Sell / Trade', place: 'bottom' },
      ),
      beat(
        'Open trade-in rates',
        'Rates are in a folded panel. I will open Trade-in rates so you can see credit and cash. Store credit from a deal stays at this shop.',
        '/admin/sell-trade',
        'trade-rates',
        'Open rates',
        { hrefLabel: 'Open Sell / Trade', place: 'right', focus: 'target', demo: { thenClick: 'trade-rates', waitFor: { expanded: 'trade-rates', target: 'Store credit %' } } },
      ),
      beat(
        'Store credit percent',
        'Store credit percent is the base rate versus market when you pay in house credit. This is what most shops lead with.',
        '/admin/sell-trade',
        'Store credit %',
        'Credit rate',
        { hrefLabel: 'Open Sell / Trade', place: 'right', prepare: { openAccordion: 'trade-rates', waitFor: { expanded: 'trade-rates', target: 'Store credit %' } } },
      ),
      beat(
        'Cash percent',
        'Cash percent is usually lower. Buy-list premium sits on top when you want to pay more for a specific list. Promo window is a weekend bump. Save rates writes them. We will not save from this lesson.',
        '/admin/sell-trade',
        'Cash %',
        'Cash rate',
        { hrefLabel: 'Open Sell / Trade', place: 'right', prepare: { openAccordion: 'trade-rates', waitFor: { expanded: 'trade-rates', target: 'Cash %' } } },
      ),
      beat(
        'Save rates when you are done',
        'Save rates is the write. Do that after you set the three columns: base, buy-list premium, and optional promo dates.',
        '/admin/sell-trade',
        'Save rates',
        'Save rates',
        { hrefLabel: 'Open Sell / Trade', place: 'left', focus: 'target', scrollTarget: 'Save rates', prepare: { openAccordion: 'trade-rates', waitFor: { expanded: 'trade-rates', target: 'Save rates' } } },
      ),
      beat(
        'Open the buy list',
        'The buy list is another folded panel. I will open it. These cards appear on the public Sell / Trade page for this store.',
        '/admin/sell-trade',
        'buy-list',
        'Open the buy list',
        { hrefLabel: 'Open Sell / Trade', place: 'right', demo: { thenClick: 'buy-list', waitFor: { expanded: 'buy-list', target: 'Add a card' } } },
      ),
      beat(
        'Add a wanted card',
        'Search the catalog in Add a card. Leave the pinned offer blank to pay your premium rate at market, or type a per-copy price to lock it. We will not add a card from this lesson.',
        '/admin/sell-trade',
        'Add a card',
        'Add a wanted card',
        { hrefLabel: 'Open Sell / Trade', place: 'right', focus: 'target', scrollTarget: 'Add a card', prepare: { waitFor: { target: 'Add a card' } } },
      ),
    ],
  },
  {
    id: 'credit',
    title: 'Store credit',
    summary: 'Credit stays at this store. Read the ledger, then adjust a balance with a note.',
    minutes: 4,
    category: 'sales',
    beats: [
      beat(
        'Open Store credit',
        'Store credit is under Commerce. Outstanding credit is money this store still owes on the ledger. It is not cash in Square and it cannot be spent at another store.',
        '/admin/store-credit',
        'Store credit',
        'Open Store credit',
        { hrefLabel: 'Open Store credit', place: 'right' },
      ),
      beat(
        'What this shop still owes',
        'Outstanding credit is the total. Use it for buylist payouts and counter corrections — not a cash-out to another location.',
        '/admin/store-credit',
        'Outstanding credit',
        'Ledger total',
        { hrefLabel: 'Open Store credit', place: 'right' },
      ),
      beat(
        'Customer balances',
        'Each row is a customer at this shop. If the list is empty, nobody has credit yet. A completed sell submission for store credit is how most balances appear.',
        '/admin/store-credit',
        'Customer balances',
        'Per-customer rows',
        { hrefLabel: 'Open Store credit', place: 'bottom' },
      ),
      beat(
        'Adjust a balance',
        'When a customer has store credit, each row gets an Adjust button. Adjust opens amount and note. Amount can be positive or negative. Add a short note so the next shift knows why. Save writes the ledger. We will not save from this lesson.',
        '/admin/store-credit',
        'Adjust|Customer balances',
        'Adjust, then Save',
        { hrefLabel: 'Open Store credit', place: 'left', focus: 'target' },
      ),
    ],
  },
  {
    id: 'branding',
    title: 'Brand the storefront',
    summary: 'Pick a palette, switch to Cards, choose gallery or compact, then check the live preview.',
    minutes: 5,
    category: 'storefront',
    beats: [
      beat(
        'Open Branding',
        'Branding saves as you go. Open it under Storefront.',
        '/admin/branding',
        'Branding',
        'Open Branding',
        { hrefLabel: 'Open Branding', place: 'right' },
      ),
      beat(
        'Start on Colors',
        'Colors is the first tab. Theme library is a whole palette in one click. Then fine-tune light and dark underneath.',
        '/admin/branding',
        'Colors',
        'Colors tab',
        { hrefLabel: 'Open Branding', place: 'bottom' },
      ),
      beat(
        'Click a palette',
        'Theme library applies a curated set. The phone preview on the right is the same storefront shoppers get. Pick one that matches the shop, then tune brand colors below.',
        '/admin/branding',
        'Theme library',
        'Click a palette',
        { hrefLabel: 'Open Branding', place: 'bottom' },
      ),
      beat(
        'Open the Cards tab',
        'Card display is on the Cards tab. I will open it so you can see Gallery versus Marketplace compact.',
        '/admin/branding',
        'Cards',
        'Open Cards',
        { hrefLabel: 'Open Branding', place: 'bottom', focus: 'target', demo: { thenClick: 'Cards', waitFor: { target: 'Gallery' } } },
      ),
      beat(
        'Gallery or compact',
        'Gallery is image-forward. Marketplace compact is denser, with price and add-to-cart on one row. Pick the one that matches how you sell in the shop.',
        '/admin/branding',
        'Gallery',
        'Gallery layout',
        { hrefLabel: 'Open Branding', place: 'right', prepare: { openTab: 'Cards', waitFor: { target: 'Gallery' } } },
      ),
      beat(
        'Marketplace compact',
        'Marketplace compact is the denser row. Use it if you want a trading-card marketplace feel. The live preview updates as you choose.',
        '/admin/branding',
        'Marketplace compact',
        'Compact layout',
        { hrefLabel: 'Open Branding', place: 'left', focus: 'target', scrollTarget: 'Marketplace compact', prepare: { openTab: 'Cards', waitFor: { target: 'Marketplace compact' } } },
      ),
      beat(
        'Check the live shop',
        'Upload a logo and a hero photo on the Hero tab. When the preview looks right, open View storefront and confirm on the real page.',
        '/admin/branding',
        'View storefront',
        'Then check the live shop',
        { hrefLabel: 'Open Branding', place: 'left', focus: 'target', scrollTarget: 'View storefront' },
      ),
    ],
  },
  {
    id: 'spotlight',
    title: 'Pin spotlight cards',
    summary: 'Save the rail, set the price floor, then pin in-stock singles that should lead.',
    minutes: 4,
    category: 'storefront',
    beats: [
      beat(
        'Open Spotlight',
        'Spotlight is the premium row on the homepage. Open it under Storefront.',
        '/admin/spotlight',
        'Spotlight',
        'Open Spotlight',
        { hrefLabel: 'Open Spotlight', place: 'right' },
      ),
      beat(
        'Save writes the rail',
        'Save spotlight writes the rail shoppers see. Change the floor or pins first, then save. We will not save from this lesson.',
        '/admin/spotlight',
        'Save spotlight',
        'Save after you change it',
        { hrefLabel: 'Open Spotlight', place: 'left' },
      ),
      beat(
        'Live storefront rail',
        'This carousel is the same one shoppers see. Pin a card to lock it at the front. Unpin to let the floor pick again.',
        '/admin/spotlight',
        'Live storefront rail',
        'What shoppers see',
        { hrefLabel: 'Open Spotlight', place: 'bottom' },
      ),
      beat(
        'Set the price floor',
        'Minimum price is the floor for automatic picks. If nothing is in stock above the floor, shoppers see an empty rail until you lower the floor or add inventory.',
        '/admin/spotlight',
        'Minimum price',
        'Price floor',
        { hrefLabel: 'Open Spotlight', place: 'bottom' },
      ),
      beat(
        'How long the rail is',
        'Minimum cards fills with the next-highest singles if not enough meet the floor. Maximum cards caps the carousel.',
        '/admin/spotlight',
        'Minimum cards',
        'Rail length',
        { hrefLabel: 'Open Spotlight', place: 'bottom' },
      ),
    ],
  },
  {
    id: 'events',
    title: 'Post events',
    summary: 'Write the community board, add a listing, pin it, then save the calendar.',
    minutes: 5,
    category: 'storefront',
    beats: [
      beat(
        'Open Events',
        'Events is the public calendar and the event-board hero. Open it under Storefront.',
        '/admin/events',
        'Events',
        'Open Events',
        { hrefLabel: 'Open Events', place: 'right' },
      ),
      beat(
        'Write the board heading',
        'Board heading appears on the event-board hero and on the public calendar. Keep it in the voice of the shop: Friday Night Magic, prereleases, commander night.',
        '/admin/events',
        'Board heading',
        'This copy is public',
        { hrefLabel: 'Open Events', place: 'right' },
      ),
      beat(
        'Intro blurb',
        'Intro blurb is the paragraph under the heading. An external calendar URL is optional if you already run Google or Discord events.',
        '/admin/events',
        'Intro blurb',
        'The public intro',
        { hrefLabel: 'Open Events', place: 'right' },
      ),
      beat(
        'Add a listing',
        'You can post up to 50 events. Title, start time, location, and details live here. Pin the ones that should stay at the top.',
        '/admin/events',
        'Add event',
        'Add the next event',
        { hrefLabel: 'Open Events', place: 'top' },
      ),
      beat(
        'Add to the board',
        'Add to board parks the draft on the list. It is not public until you save. We will not add from this lesson.',
        '/admin/events',
        'Add to board',
        'Park the draft',
        {
          hrefLabel: 'Open Events',
          place: 'left',
          focus: 'target',
          scrollTarget: 'Add to board',
          prepare: { fillTarget: 'Event title', fill: 'Friday Night Magic', waitFor: { target: 'Add to board' } },
        },
      ),
      beat(
        'Save the calendar',
        'Save events and board publishes the heading, blurb, and listings. Empty listings mean the storefront shows no upcoming events.',
        '/admin/events',
        'Save events & board',
        'Publish the calendar',
        { hrefLabel: 'Open Events', place: 'left' },
      ),
    ],
  },
  {
    id: 'team',
    title: 'Add staff',
    summary: 'Invite by email, set access, then keep the owner row as the owner.',
    minutes: 4,
    category: 'start',
    beats: [
      beat(
        'Open Users',
        'Do not share the owner password. Open Users under Storefront and add an employee with their work email.',
        '/admin/users',
        'Users',
        'Open Users',
        { hrefLabel: 'Open Users', place: 'right' },
      ),
      beat(
        'Add an employee',
        'This form creates a login. Set a password for a new account. Existing emails keep the password they already have.',
        '/admin/users',
        'Add an employee',
        'Invite form',
        { hrefLabel: 'Open Users', place: 'bottom' },
      ),
      beat(
        'Enter their email',
        'Use their work email. That is how they sign in — the same login page customers use — then they land on this store’s admin.',
        '/admin/users',
        'Employee email',
        'Work email',
        { hrefLabel: 'Open Users', place: 'right' },
      ),
      beat(
        'Admin or member',
        'Admin opens this whole dashboard. Member is for people who should not change settings. Then press Add. We will not add from this lesson.',
        '/admin/users',
        'Access',
        'Admin or member',
        { hrefLabel: 'Open Users', place: 'left' },
      ),
      beat(
        'Owner stays owner',
        'The owner row cannot be deleted from here. You can change an employee’s access or remove them when they leave.',
        '/admin/users',
        'Owner',
        'Owner cannot be removed',
        { hrefLabel: 'Open Users', place: 'top' },
      ),
    ],
  },
]
